// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDMb-KqPlLORuwiHq6KqyrRuST6Tqt1FA',
    appId: '1:732542294215:web:1b399a85fd9a28487e86e2',
    messagingSenderId: '732542294215',
    projectId: 'proyekpickupsample',
    authDomain: 'proyekpickupsample.firebaseapp.com',
    databaseURL: 'https://proyekpickupsample-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyekpickupsample.firebasestorage.app',
    measurementId: 'G-BQJ6QY5R53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfbuOrzU6QUnSGEJOZtC2rd75ezc_1ZJg',
    appId: '1:732542294215:android:8037e498847a1abb7e86e2',
    messagingSenderId: '732542294215',
    projectId: 'proyekpickupsample',
    databaseURL: 'https://proyekpickupsample-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyekpickupsample.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBW6VhcuynjVimPL3JXaTnpaIkvr0hSog',
    appId: '1:732542294215:ios:1fdd64e9ab66efda7e86e2',
    messagingSenderId: '732542294215',
    projectId: 'proyekpickupsample',
    databaseURL: 'https://proyekpickupsample-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyekpickupsample.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBW6VhcuynjVimPL3JXaTnpaIkvr0hSog',
    appId: '1:732542294215:ios:1fdd64e9ab66efda7e86e2',
    messagingSenderId: '732542294215',
    projectId: 'proyekpickupsample',
    databaseURL: 'https://proyekpickupsample-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyekpickupsample.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

}